### ISSUE TITLE
Lomiri: Flashight toggle doesn't work

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/ayatana-indicator-power#66]
Trying to use the flashlight toggle widget action on a Volla Phone (yggdrasil) with Ubuntu Touch 20.04 (r283) simply leaves the following in `journalctl -f`:
```
Nov 01 13:40:48 ubuntu-phablet repowerd[3356]: DefaultStateMachine[c1]: handle_user_activity_extending_power_state
Nov 01 13:40:48 ubuntu-phablet lomiri[2402]: g_variant_type_peek_string: assertion 'g_variant_type_check (type)' failed
Nov 01 13:40:48 ubuntu-phablet lomiri[2402]: g_variant_type_string_is_valid: assertion 'type_string != NULL' failed
Nov 01 13:40:48 ubuntu-phablet ayatana-indicat[2317]: g_simple_action_activate: assertion 'simple->parameter_type == NULL ? parameter == NULL : (parameter != NULL && g_variant_is_of_type (parameter, simple->parameter_type))' failed
```
Version: `22.2.0-1ubports1+0~20220308175505.5+ubports20.04~1.gbp651c13`

**Comment by tari01** [comment]
@JamiKettunen 

I needed to temporarily tweak some other parts of the indicator to be able to test the fix in the PDK. The switch seems to work, but it would be good to know if it's fully OK. Can I ask you to test https://github.com/AyatanaIndicators/ayatana-indicator-power/pull/68 on the phone? Thanks.
