### ISSUE TITLE
No longer shows battery status in the menu

### ISSUE THREAD

**Issue by andrewshadura** [AyatanaIndicators/ayatana-indicator-power#85]
`Failed to create IDO object` is shown instead of battery status:
![image](https://github.com/AyatanaIndicators/ayatana-indicator-power/assets/309253/0a08d546-e2d1-48f4-9647-fcb1690b6c56)

This is on Debian unstable, `ayatana-indicator-power=23.6.1-1` (same error with 23.6.0-1)

**Comment by tari01** [comment]
@andrewshadura:

Please check if you have the latest **ayatana-ido** package(s) (currently 0.10.1) and report back. Thanks.

**Comment by sunweaver** [comment]
@andrewshadura Sorry for the long response time. I am about to upload ayatana-indicator-power 24.1.0 to Debian which should solve this problem.
